### ISSUE TITLE
FK constraints with mismatched child/parent column types (int vs string-of-int codes)

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#5552]
## Summary

The `foreign_key` dbt data test currently casts both sides of an FK comparison to `VARCHAR` before joining (introduced in #5538). That issue was highlighted while trying to add FK constraints to DuckDB, which refuses to plan an `ANTI JOIN` across columns of genuinely incompatible types. Without the `CAST` the `dbt` test errors out instead of failing the test. So there were 12 FK constraints that actually weren't being tested at all (see the table below).  With the `CAST` they're being tested... insofar as "does this stringified number look like this other string" is a valid FK constraint.

The previous lazy typing behavior of SQLite and this bug in our dbt foreign key test have hidden the fact that a dozen FK relationships have a child column typed as an integer referencing a parent "code" column typed as a string, where that string just happens to contain the digits of the same integer (e.g. child value `1` matching parent value `"1"`). I mean, not totally a coincidence, but not how it's supposed to work. We actually define these coding tables with integer PKs, but they're forced to become strings by our type enforcement mechanisms, which saw the one, lonely `code` field defined as a `string`.

## Affected relationships

This is every `ForeignKey` in the compiled `Package` metadata where the declared `Field.type` of the FK column differs from the PK column it references:

| Child table | Child column | Child type | Parent table | Parent column | Parent type |
| --- | --- | --- | --- | --- | --- |
| `_core_eia860__cooling_equipment` | `steam_plant_type_code` | integer | `core_eia__codes_steam_plant_types` | `code` | string |
| `_core_eia860__fgd_equipment` | `steam_plant_type_code` | integer | `core_eia__codes_steam_plant_types` | `code` | string |
| `core_eia860__assn_boiler_generator` | `steam_plant_type_code` | integer | `core_eia__codes_steam_plant_types` | `code` | string |
| `core_eia860__scd_generators_multifuel` | `sector_id_eia` | integer | `core_eia__codes_sector_consolidated` | `code` | string |
| `core_eia860__scd_generators_wind` | `wind_quality_class` | integer | `core_eia__codes_wind_quality_class` | `code` | string |
| `core_eia860__scd_plants` | `sector_id_eia` | integer | `core_eia__codes_sector_consolidated` | `code` | string |
| `core_eia860m__changelog_generators` | `sector_id_eia` | integer | `core_eia__codes_sector_consolidated` | `code` | string |
| `core_rus12__yearly_investments` | `investment_type_code` | integer | `core_rus__codes_investment_types` | `code` | string |
| `core_rus7__yearly_investments` | `investment_type_code` | integer | `core_rus__codes_investment_types` | `code` | string |
| `out_eia__yearly_plants` | `sector_id_eia` | integer | `core_eia__codes_sector_consolidated` | `code` | string |
| `out_rus12__yearly_investments` | `investment_type_code` | integer | `core_rus__codes_investment_types` | `code` | string |
| `out_rus7__yearly_investments` | `investment_type_code` | integer | `core_rus__codes_investment_types` | `code` | string |

All 12 instances resolve to just 4 underlying coding tables:

- `core_eia__codes_steam_plant_types`
- `core_eia__codes_sector_consolidated`
- `core_eia__codes_wind_quality_class`
- `core_rus__codes_investment_types`

## Why this is bad

- We can get away with this in lazy typing systems like SQLite, but if a user (very reasonably!) wanted to read the coding table and the data table it annotates from Parquet, and then join/merge them using pandas or polars or many other tools, the join would fail and they would have to futz with the dtypes to make it work, which is bad ergonomics
- The dbt FK test currently can't distinguish "these are the same value, represented differently" from "these are genuinely different values that happen to look similar as text." Casting to text as a workaround means a *real* future type mismatch (e.g. a metadata edit that accidentally changes a column's dtype) would no longer be caught by this test either.

## Proposed fix

1. Harmonize the 4 coding tables so `code` is stored as an integer (`Int64`/`pd.Int64Dtype()`), consistent with every column that references them, rather than a string of digits. Update the code table definitions and any string literals in transform code that currently compare against the string form.
2. Add a validator to `ForeignKey`/`Schema` in `src/pudl/metadata/classes.py` that checks each FK field's declared `type` against its referenced PK field's declared `type` and raises if they're incompatible, so this kind of mismatch can't happen again.
3. Once (1) and (2) land, revert the `CAST(... AS VARCHAR)` workaround in `dbt/tests/data_tests/generic_tests/foreign_key.sql` back to a native equality comparison, since the underlying type-compatibility guarantee will be enforced upstream in metadata instead.
4. Finally, enable the FK constraints on the `pudl_duckdb` asset / database output so the DuckDB database is self-documenting and also provides a backup check that our DB schema is valid (as evidenced by this bug, not worthless!)
